;MACROS PARA POSICION Y VIDEO
CALCULAR_CENTRO MACRO ESPACIO, LONGITUD, SALIDA

    SAVE_REGS<AX>
    MOV AL, ESPACIO
    SUB AL, LONGITUD
    SHR AL, 1; ( ESPACIO - LONGITUD ) / 2

    MOV SALIDA, AL
    RESTORE_REGS<AX>
    
ENDM
