; GENERAR_MANZANAS

GENERAR_MANZANAS PROC
    SAVE_REGS <AX, BX, CX, DX, SI>
    ; GENERAR 10 MANZANAS
    MOV CX, 10          
    MOV SI, 0           
LOOP_GENERACION:
    PUSH CX
    XOR BX, BX  
REINTENTAR_MANZANA:
    MOV AH, 2CH
    INT 21H             

    MOV AL, SEMILLA
    ADD AL, DL          
    ADD AL, BL          

    PUSH DX
    MOV DX, SI         
    ADD AL, DL          
    POP DX

    MOV CL, 3
    MUL CL              
    ADD AL, 17
    MOV SEMILLA, AL

    ; X ALEATORIA
    MOV AL, SEMILLA
    MOV CL, 13
    MUL CL             
    XOR AH, AH
    MOV CL, X_LIM
    SUB CL, 3           
    DIV CL             
    ADD AH, 3           
    MOV TEMP_X, AH

    ; Y ALEATORIA
    MOV AL, SEMILLA
    ADD AL, TEMP_X
    MOV CL, 7
    MUL CL
    XOR AH, AH
    MOV CL, Y_LIM
    SUB CL, 2           
    DIV CL              
    ADD AH, 2          
    MOV TEMP_Y, AH

    ; VALIDAR QUE NO COLISIONE CON OTRA MANZANA
    CALL VALIDAR_POSICION_MANZANA
    CMP AX, 1
    JNE GUARDAR_MANZANA

    ; POSICION OCUPADA: reintentar
    INC BX
    ADD SEMILLA, 7
    JMP REINTENTAR_MANZANA

GUARDAR_MANZANA:
    MOV BX, SI          
    MOV AL, TEMP_X
    MOV MANZANAS_X[BX], AL
    MOV AL, TEMP_Y
    MOV MANZANAS_Y[BX], AL

    INC SI
    POP CX
    LOOP LOOP_GENERACION

    RESTORE_REGS <SI, DX, CX, BX, AX>
    RET
GENERAR_MANZANAS ENDP


; DIBUJAR_MANZANAS

DIBUJAR_MANZANAS PROC
    SAVE_REGS <AX, BX, CX, DX, SI>

    MOV CX, 10
    MOV SI, 0
LOOP_DIBUJO:
    PUSH CX
    MOV BX, SI
    MOV AL, MANZANAS_X[BX]
    CMP AL, 0
    JE SKIP_MANZANA

    ; POSICIONAR CURSOR
    MOV AH, 02H
    MOV BH, 0
    MOV DL, MANZANAS_X[BX]
    MOV DH, MANZANAS_Y[BX]
    INT 10H

    ; DIBUJAR BLOQUE ROJO 
    MOV AH, 09H
    MOV BH, 0
    ;BLOQUE SOLIDO
    MOV AL, 0DBH
    ;COLOR ROJO PARA LA MANZANA      
    MOV BL, 4H       
    MOV CX, 1
    INT 10H

SKIP_MANZANA:
    INC SI
    POP CX
    LOOP LOOP_DIBUJO

    RESTORE_REGS <SI, DX, CX, BX, AX>
    RET
DIBUJAR_MANZANAS ENDP


; VERIFICAR_COMER_MANZANA

VERIFICAR_COMER_MANZANA PROC
    SAVE_REGS <AX, BX, CX, DX, SI>

    MOV CX, 10
    MOV SI, 0

CICLO_VERIFICAR:
    ; REVISAR SI LA MANZANA ESTA ACTIVA
    MOV BX, SI
    MOV AL, MANZANAS_X[BX]
    CMP AL, 0
    JE SIGUIENTE_MANZANA

    ;POSICION DE LA CABEZA
    MOV BX, SNAKE_HEAD_IX
    SHL BX, 1
    MOV AX, SNAKE[BX]   ; AH=fila AL=col
    MOV BX, SI
    ; COMPARAR COLUMNA
    CMP AL, MANZANAS_X[BX]
    JNE SIGUIENTE_MANZANA
    ; COMPARAR FILA
    CMP AH, MANZANAS_Y[BX]
    JNE SIGUIENTE_MANZANA

    ;SE COMIO LA MANZANA
    INC score   ; AUMENTAR EL SCORE
    MOV DL, MANZANAS_X[BX]
    MOV DH, MANZANAS_Y[BX]
    ; MARCAR QUE YA SE LA COMIO 
    MOV MANZANAS_X[BX], 0
    MOV MANZANAS_Y[BX], 0

    ; BORRAR VISUALMENTE
    MOV AH, 02H
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV BH, 0
    MOV AL, ' '
    MOV BL, INSIDE_COLOR
    MOV CX, 1
    INT 10H

    ;HACEMOS QUE CREZCA 3 SEGMENTOS
    CALL CRECER_SNAKE
    INC MANZANAS_COMIDAS

    ;AQUI SE REGENERAN LAS 10 MANZANAS CUANDO YA SE LAS COME TODAS
    CMP MANZANAS_COMIDAS, 10
    JNE FIN_VERIFICAR
    MOV MANZANAS_COMIDAS, 0
    CALL GENERAR_MANZANAS
    JMP FIN_VERIFICAR

SIGUIENTE_MANZANA:
    INC SI
    LOOP CICLO_VERIFICAR

FIN_VERIFICAR:
    RESTORE_REGS <SI, DX, CX, BX, AX>
    RET
VERIFICAR_COMER_MANZANA ENDP


; VALIDAR_POSICION_MANZANA
VALIDAR_POSICION_MANZANA PROC
    
    SAVE_REGS <BX, CX, DX>

    MOV CX, 10
    MOV BX, 0

CICLO_VALIDAR:
    MOV AL, MANZANAS_X[BX]
    CMP AL, 0
    JE SIGUIENTE_VALIDAR
    CMP AL, TEMP_X
    JNE SIGUIENTE_VALIDAR
    MOV AL, MANZANAS_Y[BX]
    CMP AL, TEMP_Y
    JE POSICION_INVALIDA

SIGUIENTE_VALIDAR:
    INC BX
    LOOP CICLO_VALIDAR
    MOV AX, 0
    JMP FIN_VALIDAR

POSICION_INVALIDA:
    MOV AX, 1

FIN_VALIDAR:
    RESTORE_REGS <DX, CX, BX>
    RET
VALIDAR_POSICION_MANZANA ENDP
