INIT_SNAKE PROC
    SAVE_REGS <AX, BX, CX, DX>

    ; DIBUJAR COLA
    MOV AH, SNAKE_ROW_INICIAL
    MOV AL, SNAKE_COL_INICIAL
    SUB AL, 2               
    MOV SNAKE[0], AX
    MOV DH, AH
    MOV DL, AL
    MOV AL, 0DBh
    MOV BL, SNAKE_COLOR
    CALL DRAW_SEGMENT

    ; DIBUJAR SEGMENTO
    MOV AH, SNAKE_ROW_INICIAL     
    MOV AL, SNAKE_COL_INICIAL
    DEC AL                  
    MOV SNAKE[2], AX
    MOV DH, AH
    MOV DL, AL
    MOV AL, 0DBh
    MOV BL, SNAKE_COLOR
    CALL DRAW_SEGMENT

    ; DIBUJAR CABEZA
    MOV AH, SNAKE_ROW_INICIAL
    MOV AL, SNAKE_COL_INICIAL     
    MOV SNAKE[4], AX
    MOV DH, AH
    MOV DL, AL
    MOV AL, 0DBh
    MOV BL, SNAKE_COLOR
    CALL DRAW_SEGMENT

    MOV SNAKE_HEAD_IX, 2
    MOV SNAKE_TAIL_IX, 0
    MOV AX, SNAKE[0]
    MOV SNAKE_ERASE_POS, AX

    RESTORE_REGS <DX, CX, BX, AX>
    RET
INIT_SNAKE ENDP
DRAW_SEGMENT PROC
    SAVE_REGS <AX, BX, CX, DX>
    ; MOVER CURSOR
    MOV AH, 02H
    MOV BH, 0
    INT 10H

    ; IMPRIMIR
    MOV AH, 09H
    MOV BH, 0
    MOV CX, 1
    INT 10H

    RESTORE_REGS <DX, CX, BX, AX>
    RET
DRAW_SEGMENT ENDP

DRAW_SNAKE PROC
    SAVE_REGS <AX,BX,CX,DX,SI>

    ; DIBUJAR CABEZA
    MOV SI, SNAKE_HEAD_IX
    SHL SI, 1
    MOV AX, SNAKE[SI]
    MOV DH, AH              ; FILA
    MOV DL, AL              ; COLUMNA
    MOV AL, 0DBh            ; CARACTER
    MOV BL, SNAKE_COLOR     ; COLOR
    CALL DRAW_SEGMENT

    ; BORRAR COLA
    MOV AX, SNAKE_ERASE_POS
    MOV DH, AH
    MOV DL, AL
    MOV AL, ' '
    MOV BL, INSIDE_COLOR
    CALL DRAW_SEGMENT
    
    RESTORE_REGS <SI,DX,CX,BX,AX>
    RET
DRAW_SNAKE ENDP

MOVE_SNAKE PROC
    SAVE_REGS <AX,BX,CX,DX,SI>

    ; NUEVA POSICION DE LA CABEZA
    MOV SI, SNAKE_HEAD_IX
    SHL SI, 1
    MOV AX, SNAKE[SI]
    CMP SNAKE_DIRECTION, 0
    JNE .CHECK_RIGHT
    DEC AH
    JMP .NUEVA_POS

.CHECK_RIGHT:
    CMP SNAKE_DIRECTION, 1
    JNE .CHECK_DOWN
    INC AL
    JMP .NUEVA_POS
.CHECK_DOWN:

    CMP SNAKE_DIRECTION, 2
    JNE .CHECK_LEFT
    INC AH
    JMP .NUEVA_POS
.CHECK_LEFT:

    DEC AL
.NUEVA_POS:

    ;DECTAR ERRORES POR LOS BORDES
    CMP AH, 1       
    JL .CHOQUE
    CMP AH, 23       
    JG .CHOQUE
    CMP AL, 2       
    JL .CHOQUE
    CMP AL, 77       
    JG .CHOQUE
    
    ; INSERTAR NUEVA CABEZA
    MOV BX, SNAKE_HEAD_IX
    INC BX
    CMP BX, SNAKE_MAX_LEN
    JL  .OK_HEAD
    MOV BX, 0

.OK_HEAD:
    MOV SNAKE_HEAD_IX, BX
    MOV SI, BX
    SHL SI, 1
    MOV SNAKE[SI], AX

    ; GUARDAR POSICION VIEJA DE LA COLA
    MOV BX, SNAKE_TAIL_IX
    MOV SI, BX
    SHL SI, 1
    MOV AX, SNAKE[SI]
    MOV SNAKE_ERASE_POS, AX

    ; AVANZAR SNAKE_TAIL_IX
    INC BX
    CMP BX, SNAKE_MAX_LEN
    JL  .OK_TAIL
    MOV BX, 0
.OK_TAIL:
    MOV SNAKE_TAIL_IX, BX

    RESTORE_REGS <SI,DX,CX,BX,AX>
    RET
    
;ACCION CHOCAR
.CHOQUE:
    MOV AH, 02H
    MOV BH, 0
    MOV DH, 12       
    MOV DL, 30       
    INT 10H

    MOV AH, 09H
    LEA DX, MSJ_FIN
    INT 21H

    MOV AH, 4CH
    INT 21H
MOVE_SNAKE ENDP
